version: "2"
services:
  aws-ot-collector:
    container_name: aws-ot-collector
    hostname: aws-ot-collector
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: 
      - --config=/etc/otel-config.yaml
    environment:
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: < AWS ACCESS KEY ID >
      AWS_SECRET_ACCESS_KEY: < AWS SECRET ACCESS KEY >
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - 4317:4317  
    networks:
      - aws-ot-collector

networks:
  aws-ot-collector: {}